(function(){"use strict";var cfg=window.SUPABASE_CONFIG||null;var sb=null;var user=null;var entitled=false;var listeners=[];function ready(){return!!sb;}
function bucket(){return(cfg&&cfg.bucket)||"paid-songs";}
function notify(){listeners.forEach(function(fn){try{fn();}catch(e){}});}
function mkErr(code,msg){var e=new Error(msg||code);e.code=code;return e;}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
var SB_CDN="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";var _sbLoad=null;function configOk(){return!(!cfg||!cfg.url||!cfg.anonKey||/貼上/.test(cfg.url)||/貼上/.test(cfg.anonKey));}
function loadSbScript(){if(window.supabase&&window.supabase.createClient)return Promise.resolve();return new Promise(function(resolve,reject){var s=document.createElement("script");s.src=SB_CDN;s.onload=function(){resolve();};s.onerror=function(){reject(new Error("supabase load fail"));};document.head.appendChild(s);});}
function ensureClient(){if(sb)return Promise.resolve(sb);if(_sbLoad)return _sbLoad;if(!configOk())return Promise.resolve(null);_sbLoad=loadSbScript().then(function(){if(!window.supabase||!window.supabase.createClient)throw new Error("no supabase");sb=window.supabase.createClient(cfg.url,cfg.anonKey);sb.auth.onAuthStateChange(function(_ev,session){applyUser(session?session.user:null);});return sb;}).catch(function(){_sbLoad=null;setStatusText("（登入元件載入失敗，請檢查網路連線）");return null;});return _sbLoad;}
function hasSession(){if(!configOk())return false;try{var m=/https?:\/\/([^.]+)\./.exec(cfg.url),ref=m?m[1]:"";if(ref&&localStorage.getItem("sb-"+ref+"-auth-token"))return true;for(var i=0;i<localStorage.length;i++){if(/^sb-.*-auth-token$/.test(localStorage.key(i)))return true;}}catch(e){}
return false;}
function warmup(){return ensureClient();}
function init(){wireUI();if(!configOk()){setStatusText("（登入服務尚未設定——請先照「後端設定指南」填好 supabase-config.js）");return;}
renderUI();if(hasSession()){ensureClient().then(function(c){if(!c)return;c.auth.getSession().then(function(res){applyUser(res&&res.data&&res.data.session?res.data.session.user:null);});});}}
function applyUser(u){user=u||null;if(!user){entitled=false;renderUI();notify();return;}
checkEntitlement().then(function(ok){entitled=ok;renderUI();notify();});}
function checkEntitlement(){if(!sb||!user)return Promise.resolve(false);var email=(user.email||"").toLowerCase();return sb.from("allowed_emails").select("active").eq("email",email).maybeSingle().then(function(res){return!!(res&&res.data&&res.data.active);}).catch(function(){return false;});}
function signIn(email){email=(email||"").trim();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)){setStatusText("請輸入正確的 Email。");return;}
setStatusText("寄送登入連結中…");ensureClient().then(function(c){if(!c){setStatusText("登入服務尚未設定或載入失敗。");return;}
c.auth.signInWithOtp({email:email,options:{emailRedirectTo:location.origin+location.pathname}}).then(function(res){if(res.error)setStatusText("寄送失敗："+res.error.message);else setStatusText("已寄出登入連結到 "+email+"，請到信箱點連結（用「同一個瀏覽器」打開）。");});});}
function signOut(){if(sb)sb.auth.signOut();}
function downloadPaidSong(path){if(!user)return Promise.reject(mkErr("NOT_LOGGED_IN","尚未登入"));return downloadSong(bucket(),path);}
function downloadSong(bkt,path){return ensureClient().then(function(c){if(!c)throw mkErr("NOT_READY","登入服務尚未設定");return c.storage.from(bkt).download(path).then(function(res){if(res.error||!res.data)throw mkErr("NOT_ENTITLED",(res.error&&res.error.message)||"無法下載（可能尚未開通）");return res.data.arrayBuffer();});});}
function fetchCatalog(){return ensureClient().then(function(c){if(!c)return[];return c.from("songs").select("title,grp,bucket,path,tier,sort").order("sort").order("title").then(function(res){return(res&&res.data)?res.data:[];}).catch(function(){return[];});});}
function checkEmailUnlock(email){email=(email||"").trim().toLowerCase();if(!email)return Promise.resolve(false);return ensureClient().then(function(c){if(!c)return false;return c.rpc("email_unlocked",{p_email:email}).then(function(res){if(res.error)return null;return!!res.data;}).catch(function(){return null;});});}
function registerDevice(email,device){email=(email||"").trim().toLowerCase();if(!email||!device)return Promise.resolve(null);return ensureClient().then(function(c){if(!c)return null;return c.rpc("register_device",{p_email:email,p_device:device}).then(function(res){return res.error?null:res.data;}).catch(function(){return null;});});}
function unregisterDevice(email,device){email=(email||"").trim().toLowerCase();if(!email||!device)return Promise.resolve(false);return ensureClient().then(function(c){if(!c)return false;return c.rpc("unregister_device",{p_email:email,p_device:device}).then(function(res){return!res.error;}).catch(function(){return false;});});}
function resetDevices(email){email=(email||"").trim().toLowerCase();if(!email)return Promise.resolve(null);return ensureClient().then(function(c){if(!c)return null;return c.rpc("reset_devices",{p_email:email}).then(function(res){return res.error?null:res.data;}).catch(function(){return null;});});}
function getCharUnlocks(email){email=(email||"").trim().toLowerCase();if(!email)return Promise.resolve(null);return ensureClient().then(function(c){if(!c)return null;return c.rpc("get_char_unlocks",{p_email:email}).then(function(res){return res.error?null:(res.data||null);}).catch(function(){return null;});});}
function saveCharUnlocks(email,data){email=(email||"").trim().toLowerCase();if(!email)return Promise.resolve(false);return ensureClient().then(function(c){if(!c)return false;return c.rpc("save_char_unlocks",{p_email:email,p_data:data||{}}).then(function(res){return!res.error;}).catch(function(){return false;});});}
function fetchFolders(){return ensureClient().then(function(c){if(!c)return{};return c.from("paid_folders").select("grp,locked,pw_hash").then(function(res){var m={};(res&&res.data?res.data:[]).forEach(function(r){m[r.grp]={locked:!!r.locked,pw_hash:r.pw_hash||""};});return m;}).catch(function(){return{};});});}
var el={};function wireUI(){el.status=document.getElementById("acctStatus");el.email=document.getElementById("acctEmail");el.loginBtn=document.getElementById("acctLoginBtn");el.logoutBtn=document.getElementById("acctLogoutBtn");el.loginBox=document.getElementById("acctLoginBox");if(el.loginBtn)el.loginBtn.addEventListener("click",function(){signIn(el.email?el.email.value:"");});if(el.email)el.email.addEventListener("keydown",function(e){if(e.key==="Enter")signIn(el.email.value);});if(el.logoutBtn)el.logoutBtn.addEventListener("click",signOut);renderUI();}
function setStatusText(t){if(el.status)el.status.textContent=t;}
function renderUI(){if(!el.status)return;if(user){el.status.innerHTML="已登入："+escapeHtml(user.email)+
(entitled?" · <b style='color:#7CFC9B'>教材已開通 ✓</b>":" · <span style='color:#ffb454'>教材尚未開通（付款後老師會幫你開通）</span>");if(el.loginBox)el.loginBox.style.display="none";if(el.logoutBtn)el.logoutBtn.style.display="";}else{if(ready())setStatusText("未登入（免費曲可直接玩；教材需登入並開通）");if(el.loginBox)el.loginBox.style.display="";if(el.logoutBtn)el.logoutBtn.style.display="none";}}
function focusLogin(){if(el.email){try{el.email.focus();el.email.scrollIntoView({block:"center"});}catch(e){}}}
window.JianpuAuth={isReady:ready,hasSession:hasSession,warmup:warmup,getUser:function(){return user;},isEntitled:function(){return entitled;},signIn:signIn,signOut:signOut,downloadPaidSong:downloadPaidSong,downloadSong:downloadSong,fetchCatalog:fetchCatalog,fetchFolders:fetchFolders,checkEmailUnlock:checkEmailUnlock,registerDevice:registerDevice,resetDevices:resetDevices,unregisterDevice:unregisterDevice,getCharUnlocks:getCharUnlocks,saveCharUnlocks:saveCharUnlocks,onChange:function(fn){if(typeof fn==="function")listeners.push(fn);},focusLogin:focusLogin};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();})();