(function(){"use strict";var QUARTER=960;var WHOLE=QUARTER*4;function beatTicks(beat){var d=beat.duration;var base=d>0?WHOLE/d:WHOLE*(-d);if(beat.dots===1)base*=1.5;else if(beat.dots>=2)base*=1.75;var tn=beat.tupletNumerator,td=beat.tupletDenominator;if(tn&&td&&tn>0&&td>0&&tn!==td)base*=td/tn;return base;}
function barTicks(masterBar){var num=masterBar.timeSignatureNumerator||4;var den=masterBar.timeSignatureDenominator||4;return WHOLE*num/den;}
function topNoteMidi(beat){if(!beat.notes||beat.notes.length===0)return null;var best=null;for(var i=0;i<beat.notes.length;i++){var n=beat.notes[i];if(n.isTieDestination)continue;if(n.isDead)continue;var v=(typeof n.realValue==="number")?n.realValue:null;if(v==null)continue;if(best==null||v>best)best=v;}
return best;}
function topNoteInfo(beat){if(!beat.notes||beat.notes.length===0)return null;var bestNote=null;for(var i=0;i<beat.notes.length;i++){var n=beat.notes[i];if(n.isTieDestination||n.isDead)continue;if(typeof n.realValue!=="number")continue;if(bestNote==null||n.realValue>bestNote.realValue)bestNote=n;}
if(!bestNote)return null;var bend=0;if(bestNote.hasBend&&bestNote.bendPoints&&bestNote.bendPoints.length){for(var b=0;b<bestNote.bendPoints.length;b++){if(bestNote.bendPoints[b].value>bend)bend=bestNote.bendPoints[b].value;}}
return{midi:bestNote.realValue,bend:bend};}
function isGrace(beat){return!!beat.graceType&&beat.graceType!==0;}
function beatPos(beat,barStart,fallbackTick){var ps=beat.playbackStart,pd=beat.playbackDuration;if(typeof ps==="number"&&typeof pd==="number"&&pd>0){return{start:barStart+ps,ticks:pd};}
var bt=beatTicks(beat);if(isGrace(beat)){var len=Math.min(bt,WHOLE/16);return{start:Math.max(barStart,fallbackTick-len),ticks:len};}
return{start:fallbackTick,ticks:bt};}
function advance(beat,tick){return isGrace(beat)?tick:tick+beatTicks(beat);}
function tempoAutomationValue(beat){var autos=beat.automations;if(!autos||!autos.length)return null;var TEMPO=0;try{if(window.alphaTab&&alphaTab.model&&alphaTab.model.AutomationType){TEMPO=alphaTab.model.AutomationType.Tempo;}}catch(e){}
for(var i=0;i<autos.length;i++){if(autos[i].type===TEMPO)return autos[i].value;}
return null;}
function listTracks(score){var out=[];for(var t=0;t<score.tracks.length;t++){var track=score.tracks[t];var staff=track.staves[0];var isPerc=staff&&(staff.isPercussion||(staff.showTablature===false&&staff.isPercussion));var count=0;if(staff){for(var b=0;b<staff.bars.length;b++){var voice=staff.bars[b].voices[0];if(!voice)continue;for(var k=0;k<voice.beats.length;k++){if(!voice.beats[k].isRest&&topNoteMidi(voice.beats[k])!=null)count++;}}}
out.push({index:t,name:track.name||("Track "+(t+1)),noteCount:count,isPercussion:!!isPerc});}
return out;}
function buildTempoMap(score,staff){var events=[{tick:0,bpm:score.tempo||120}];var barStart=0;for(var b=0;b<staff.bars.length;b++){var mb=score.masterBars[b];var voice=staff.bars[b].voices[0];var tick=barStart;if(voice){for(var k=0;k<voice.beats.length;k++){var beat=voice.beats[k];var bpm=tempoAutomationValue(beat);if(bpm!=null)events.push({tick:beatPos(beat,barStart,tick).start,bpm:bpm});tick=advance(beat,tick);}}
barStart+=barTicks(mb);}
events.sort(function(a,b){return a.tick-b.tick;});var dedup=[];for(var i=0;i<events.length;i++){if(dedup.length&&dedup[dedup.length-1].tick===events[i].tick)dedup[dedup.length-1]=events[i];else dedup.push(events[i]);}
return dedup;}
function makeTickToSec(tempoMap){var segs=[];var sec=0;for(var i=0;i<tempoMap.length;i++){var startTick=tempoMap[i].tick;var bpm=tempoMap[i].bpm||120;var secPerTick=60/bpm/QUARTER;segs.push({tick:startTick,sec:sec,secPerTick:secPerTick});if(i+1<tempoMap.length){var span=tempoMap[i+1].tick-startTick;sec+=span*secPerTick;}}
return function(tick){var seg=segs[0];for(var j=0;j<segs.length;j++){if(segs[j].tick<=tick)seg=segs[j];else break;}
return seg.sec+(tick-seg.tick)*seg.secPerTick;};}
function buildTimeline(score,trackIndex){var track=score.tracks[trackIndex];var staff=track.staves[0];var tempoMap=buildTempoMap(score,staff);var tickToSec=makeTickToSec(tempoMap);var firstMb=score.masterBars[0];var keySig=firstMb?(firstMb.keySignature||0):0;var tonicPc=window.Theory.sigToTonicPc(keySig);var notes=[];var barStart=0;for(var b=0;b<staff.bars.length;b++){var mb=score.masterBars[b];var voice=staff.bars[b].voices[0];var tick=barStart;if(voice){for(var k=0;k<voice.beats.length;k++){var beat=voice.beats[k];var pos=beatPos(beat,barStart,tick);if(!beat.isRest){var top=topNoteInfo(beat);if(top!=null){var gr=isGrace(beat);var t0=tickToSec(pos.start);var t1=tickToSec(pos.start+pos.ticks);notes.push({time:t0,dur:Math.max(gr?0.05:0.08,t1-t0),midi:top.midi,bend:top.bend,grace:gr});}}
tick=advance(beat,tick);}}
barStart+=barTicks(mb);}
notes.sort(function(a,b){return a.time-b.time;});var totalTicks=barStart;var durationSec=tickToSec(totalTicks);return{title:(score.title||"").trim()||"未命名樂曲",artist:(score.artist||"").trim(),tempo:score.tempo||120,keySig:keySig,tonicPc:tonicPc,trackName:track.name||("Track "+(trackIndex+1)),notes:notes,durationSec:durationSec};}
function buildTabTimeline(score,trackIndex){var track=score.tracks[trackIndex];var staff=track.staves[0];var tempoMap=buildTempoMap(score,staff);var tickToSec=makeTickToSec(tempoMap);var tuning=(staff.tuning&&staff.tuning.length)?staff.tuning.slice():[64,59,55,50,45,40];var stringCount=tuning.length;var firstMb=score.masterBars[0];var keySig=firstMb?(firstMb.keySignature||0):0;var tonicPc=window.Theory.sigToTonicPc(keySig);var beats=[];var barStarts=[];var maxFret=0;var barStart=0;var tupletGroups=[];for(var b=0;b<staff.bars.length;b++){var mb=score.masterBars[b];barStarts.push(tickToSec(barStart));var voice=staff.bars[b].voices[0];var tick=barStart;if(voice){for(var k=0;k<voice.beats.length;k++){var beat=voice.beats[k];var pos=beatPos(beat,barStart,tick);if(!beat.isRest&&beat.notes&&beat.notes.length){var ns=[],deadNs=[];for(var i=0;i<beat.notes.length;i++){var n=beat.notes[i];if(n.isTieDestination)continue;if(n.isDead){deadNs.push({string:(typeof n.string==="number"?n.string:1),fret:(typeof n.fret==="number"?n.fret:0)});continue;}
if(typeof n.realValue!=="number")continue;var bend=0;if(n.hasBend&&n.bendPoints&&n.bendPoints.length){for(var bp=0;bp<n.bendPoints.length;bp++){if(n.bendPoints[bp].value>bend)bend=n.bendPoints[bp].value;}}
var fr=(typeof n.fret==="number"?n.fret:0);if(fr>maxFret)maxFret=fr;ns.push({string:(typeof n.string==="number"?n.string:1),fret:fr,midi:n.realValue,bend:bend,hammerOrigin:!!n.isHammerPullOrigin,hammerDest:!!n.isHammerPullDestination,slideOut:n.slideOutType||0,slideIn:n.slideInType||0,vibrato:n.vibrato||0,palmMute:!!n.isPalmMute,harmonic:n.harmonicType||0,trill:!!n.isTrill,letRing:!!n.isLetRing,staccato:!!n.isStaccato,tapLH:!!n.isLeftHandTapped});}
var chordName="",chordFrets=null,chordFirst=0;try{var ch=beat.chord;if(ch){if(ch.name)chordName=String(ch.name);if(ch.strings&&ch.strings.length)chordFrets=[].slice.call(ch.strings);if(typeof ch.firstFret==="number")chordFirst=ch.firstFret;}}catch(e){}
if(ns.length||deadNs.length){var t0=tickToSec(pos.start);var t1=tickToSec(pos.start+pos.ticks);var tup=null,tn=beat.tupletNumerator,td=beat.tupletDenominator;if(tn&&td&&tn>0&&td>0&&tn!==td){var gid=-1,grp=beat.tupletGroup;if(grp){gid=tupletGroups.indexOf(grp);if(gid<0){gid=tupletGroups.length;tupletGroups.push(grp);}}
tup={n:tn,d:td,gid:gid};}
beats.push({time:t0,dur:Math.max(isGrace(beat)?0.05:0.08,t1-t0),notes:ns,dead:deadNs,bar:b,grace:isGrace(beat),chord:chordName,chordFrets:chordFrets,chordFirst:chordFirst,nv:beat.duration,dots:beat.dots||0,tuplet:tup,tap:!!beat.tap,tremolo:(beat.tremoloSpeed!=null),slap:!!beat.slap,pop:!!beat.pop});}}else if(beat.isRest){var rt0=tickToSec(pos.start),rt1=tickToSec(pos.start+pos.ticks);beats.push({time:rt0,dur:Math.max(0.08,rt1-rt0),notes:[],dead:[],bar:b,rest:true,nv:beat.duration,dots:beat.dots||0,tuplet:null});}
tick=advance(beat,tick);}}
barStart+=barTicks(mb);}
beats.sort(function(a,b){return a.time-b.time;});for(var bi=0;bi<beats.length;bi++){var ns2=beats[bi].notes;for(var ni=0;ni<ns2.length;ni++){var origin=ns2[ni];if(!origin.hammerOrigin)continue;for(var bj=bi+1;bj<beats.length&&!origin.link;bj++){for(var nk=0;nk<beats[bj].notes.length;nk++){var cand=beats[bj].notes[nk];if(cand.string===origin.string){origin.link={time:beats[bj].time,midi:cand.midi,fret:cand.fret,string:cand.string};break;}}}}}
return{title:(score.title||"").trim()||"未命名樂曲",artist:(score.artist||"").trim(),tempo:score.tempo||120,keySig:keySig,tonicPc:tonicPc,trackName:track.name||("Track "+(trackIndex+1)),tuning:tuning,stringCount:stringCount,beats:beats,barStarts:barStarts,barCount:staff.bars.length,maxFret:maxFret,durationSec:tickToSec(barStart)};}
function parseBytes(arrayBuffer){if(!window.alphaTab||!alphaTab.importer||!alphaTab.importer.ScoreLoader){throw new Error("alphaTab 尚未載入");}
var bytes=new Uint8Array(arrayBuffer);return alphaTab.importer.ScoreLoader.loadScoreFromBytes(bytes);}
window.GPLoader={parseBytes:parseBytes,listTracks:listTracks,buildTimeline:buildTimeline,buildTabTimeline:buildTabTimeline};})();