(function(){"use strict";var LETTER_TO_PC={C:0,D:2,E:4,F:5,G:7,A:9,B:11};var MAJOR_STEPS=[0,2,4,5,7,9,11];var SEMITONE_TO_DEG=[{degree:1,alter:0},{degree:1,alter:1},{degree:2,alter:0},{degree:3,alter:-1},{degree:3,alter:0},{degree:4,alter:0},{degree:4,alter:1},{degree:5,alter:0},{degree:6,alter:-1},{degree:6,alter:0},{degree:7,alter:-1},{degree:7,alter:0}];var KEY_OPTIONS=[{value:"C",label:"C 大調（無升降）",pc:0,sig:0},{value:"G",label:"G 大調（1♯）",pc:7,sig:1},{value:"D",label:"D 大調（2♯）",pc:2,sig:2},{value:"A",label:"A 大調（3♯）",pc:9,sig:3},{value:"E",label:"E 大調（4♯）",pc:4,sig:4},{value:"B",label:"B 大調（5♯）",pc:11,sig:5},{value:"F#",label:"F♯大調（6♯）",pc:6,sig:6},{value:"Db",label:"D♭大調（5♭）",pc:1,sig:-5},{value:"Ab",label:"A♭大調（4♭）",pc:8,sig:-4},{value:"Eb",label:"E♭大調（3♭）",pc:3,sig:-3},{value:"Bb",label:"B♭大調（2♭）",pc:10,sig:-2},{value:"F",label:"F 大調（1♭）",pc:5,sig:-1}];function sigToTonicPc(sig){return(((sig*7)%12)+12)%12;}
function tonicPcToKeyValue(pc){for(var i=0;i<KEY_OPTIONS.length;i++){if(KEY_OPTIONS[i].pc===pc)return KEY_OPTIONS[i].value;}
return"C";}
function keyValueToPc(value){for(var i=0;i<KEY_OPTIONS.length;i++){if(KEY_OPTIONS[i].value===value)return KEY_OPTIONS[i].pc;}
return 0;}
function accSymbol(alter){if(alter===0)return"";if(alter===1)return"♯";if(alter===-1)return"♭";if(alter===2)return"𝄪";if(alter===-2)return"♭♭";return alter>0?new Array(alter+1).join("♯"):new Array(-alter+1).join("♭");}
function midiToDegree(midi,tonicPc){var s=(((midi-tonicPc)%12)+12)%12;return SEMITONE_TO_DEG[s];}
function makeOctaveOffsetFn(midis,tonicPc){var valid=midis.filter(function(m){return m!=null;}).slice().sort(function(a,b){return a-b;});if(valid.length===0)return function(){return 0;};var median=valid[Math.floor(valid.length/2)];var refMidi=tonicPc;while(refMidi+12<=median)refMidi+=12;while(refMidi>median)refMidi-=12;return function(midi){if(midi==null)return 0;return Math.floor((midi-refMidi)/12);};}
function label(midi,tonicPc,octaveOffset){var d=midiToDegree(midi,tonicPc);return{degree:d.degree,alter:d.alter,octaveOffset:octaveOffset||0,symbol:accSymbol(d.alter),text:String(d.degree)};}
window.Theory={LETTER_TO_PC:LETTER_TO_PC,MAJOR_STEPS:MAJOR_STEPS,KEY_OPTIONS:KEY_OPTIONS,sigToTonicPc:sigToTonicPc,tonicPcToKeyValue:tonicPcToKeyValue,keyValueToPc:keyValueToPc,accSymbol:accSymbol,midiToDegree:midiToDegree,makeOctaveOffsetFn:makeOctaveOffsetFn,label:label};})();